### ISSUE TITLE
upgrading from OAuth1 to OAuth2

### ISSUE THREAD

**Issue by pm-docuvive** [beaulebens/keyring#19]
I'm getting errors connecting to LinkedIn, and it appears to be because the current version of Keyring still uses OAuth1 for this service, when the standard is now OAuth2. Could somebody more knowledgeable than me please upgrade the LinkedIn service to use OAuth2?

**Comment by beaulebens** [comment]
Hi, I just checked, and OAuth1 appears to work fine for me, _however_ I noticed that the `scope` being requested appears to be different/incorrect now. I changed line 51 of the service definition (`/includes/services/extended/linkedin.php`) so that it looks like this:

`$permissions = 'r_basicprofile';`

and then I was able to successfully connect. Can you please try that, and confirm it works?

**Comment by pm-docuvive** [comment]
Many thanks – I applied your correction and it works perfectly!
